openapi: 3.0.0
info:
  title: Quiz Game API
  version: 1.0.0
paths:
  /games:
    post:
      summary: Create a new game session
      responses:
        '201':
          description: Game session created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameSession'
  /games/{gameId}/players:
    post:
      summary: Join a game session
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Player information
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Player joined
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
components:
  schemas:
    GameSession:
      type: object
      properties:
        id:
          type: string
        code:
          type: string
        status:
          type: string
          enum: [ waiting, active, finished ]
        currentQuestionId:
          type: string
        startTime:
          type: string
          format: date-time

    Player:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        score:
          type: integer
        joinedAt:
          type: string
          format: date-time

    Question:
      type: object
      properties:
        id:
          type: string
        text:
          type: string
        options:
          type: array
          items:
            type: string
        timeLimit:
          type: integer
          description: Time limit in seconds

    Answer:
      type: object
      properties:
        playerId:
          type: string
        questionId:
          type: string
        selectedOption:
          type: integer
        responseTime:
          type: integer
          description: Response time in milliseconds

    LeaderboardEntry:
      type: object
      properties:
        playerId:
          type: string
        name:
          type: string
        score:
          type: integer
