# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main"
include_ext = ["go"]
exclude_dir = ["vendor", "tmp"]
exclude_file = ["*_test.go"]

[log]
level = "debug"

[watcher]
watch = ["."]
ignore = ["tmp", "vendor"]
